language: python
addons:
  apt:
    sources:
      - llvm-toolchain-precise-3.8
      - ubuntu-toolchain-r-test
    packages:
      - clang-format-3.8
python:
  - "3.8"
install:
  - pushd /tmp
  - wget https://github.com/protocolbuffers/protobuf/releases/download/v3.15.8/protoc-3.15.8-linux-x86_64.zip
  - unzip protoc-3.15.8-linux-x86_64.zip
  - popd
  - export PATH=/tmp/bin:$PATH
script:
  # Build all test...
  - chmod +x ./compile_base.py
  # Generates remaster_all(), base(), generate_new(), generate_files(), out_mode(cpp)...
  - ./compile_base.py -g -b -gf
  #  - ./compile_base.py -l cpp -k
  #  - ./compile_base.py -l csharp -k
  #  - ./compile_base.py -l java -k
  #  - ./compile_base.py -l js -k
  #  - ./compile_base.py -l python -k
  #  - ./compile_base.py -l php -k
  #  - ./compile_base.py -l objc -k
  #  - ./compile_base.py -l ruby -k
  #  - ./compile_base.py -l swif -k
  - clang-format-3.8 -i -style file $(find base -name "base.proto")
  # - git diff --exit-code
